backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads" # Folder for media uploads
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }